name: test
channels:
  - conda-forge
dependencies:
  - scipy
  - matplotlib
  - pandas
  - h5py
  - coverage
  - setuptools
  - mne-base
  - numpydoc
  - pytest
  - pytest-cov
  - pytest-timeout
  - flaky
  - pillow
  - joblib
  - ffmpeg<6
# Do pip separately
