name: test
channels:
- conda-forge
dependencies:
- scipy
- matplotlib
- pandas
- h5py
- coverage
- setuptools
- mne-base
- numpydoc
- pytest
- pytest-cov
- pytest-timeout
- pillow
- joblib
- codecov
# Do pip separately
