name: test
channels:
- conda-forge
dependencies:
- scipy
- matplotlib
- pandas
- h5py
- coverage
- setuptools
- mne-base
- numpydoc
- pytest
- pytest-cov
- pytest-timeout
- pillow
- joblib
- ffmpeg
- codecov
- pip:
  - sounddevice
  - pyglet<1.6  # conda is stuck on 1.5.16
  - rtmixer
