name: test
channels:
- conda-forge
dependencies:
- scipy
- matplotlib
- pandas
- h5py
- coverage
- setuptools
- mne-base
- numpydoc
- pytest
- pytest-cov
- pytest-timeout
- pillow
- pyglet<1.6
- joblib
- ffmpeg
- codecov
- pip:
  - sounddevice
  - rtmixer
