[tool.codespell]
ignore-words = "ignore_words.txt"
builtin = "clear,rare,informal,names,usage"
skip = "doc/references.bib"

[tool.ruff]
exclude = ["__init__.py"]

[tool.ruff.lint]
select = ["A", "B006", "D", "E", "F", "I", "W", "UP"]  # , "UP031"]
ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D400", # First line should end with a period
    "D401", # First line should be in imperative mood
    "D413", # Missing blank line after last section
    "UP031", # Use format specifiers instead of percent format
    "UP030", # Use implicit references for positional format fields
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
ignore-decorators = [
    "property",
    "setter",
    "mne.utils.copy_function_doc_to_method_doc",
    "mne.utils.copy_doc",
    "mne.utils.deprecated",
]

[tool.ruff.lint.per-file-ignores]
"examples/**.py" = [
    "D205", # 1 blank line required between summary line and description
]

[tool.pytest.ini_options]
# -r f (failed), E (error), s (skipped), x (xfail), X (xpassed), w (warnings)
# don't put in xfail for pytest 8.0+ because then it prints the tracebacks,
# which look like real errors
addopts = """--durations=20 --doctest-modules -rfEXs --cov-report= --tb=short \
    --cov-branch --doctest-ignore-import-errors --junit-xml=junit-results.xml \
    --ignore=doc --ignore=examples --ignore=tools \
    --color=yes --capture=sys"""
junit_family = "xunit2"
# Set this pretty low to ensure we do not by default add really long tests,
# or make changes that make things a lot slower
timeout = 10
usefixtures = "matplotlib_config"
# Once SciPy updates not to have non-integer and non-tuple errors (1.2.0) we
# should remove them from here.
# This list should also be considered alongside reset_warnings in doc/conf.py
filterwarnings = '''
    error::
    ignore::ImportWarning
    ignore:TDT is in dummy mode:UserWarning
    ignore:generator 'ZipRunIterator.ranges' raised StopIteration:DeprecationWarning
    ignore:size changed:RuntimeWarning
    ignore:Using or importing the ABCs:DeprecationWarning
    ignore:joblib not installed:RuntimeWarning
    ignore:Matplotlib is building the font cache using fc-list:UserWarning
    ignore:.*clock has been deprecated.*:DeprecationWarning
    ignore:the imp module is deprecated.*:DeprecationWarning
    ignore:.*eos_action is deprecated.*:DeprecationWarning
    ignore:.*Vertex attribute shorthand.*:
    ignore:.*ufunc size changed.*:RuntimeWarning
    ignore:.*doc-files.*:
    ignore:.*include is ignored because.*:
    always:.*unclosed file.*:ResourceWarning
    always:.*may indicate binary incompatibility.*:
    ignore:.*Cannot change thread mode after it is set.*:UserWarning
    ignore:.*distutils Version classes are deprecated.*:DeprecationWarning
    ignore:.*distutils\.sysconfig module is deprecated.*:DeprecationWarning
    ignore:.*isSet\(\) is deprecated.*:DeprecationWarning
    ignore:`product` is deprecated as of NumPy.*:DeprecationWarning
    ignore:Invalid dash-separated options.*:
    ignore:__array__ implementation doesn.*:DeprecationWarning
    always:.*Exception ignored in.*__del__.*:
'''

[tool.rstcheck]
report_level = "WARNING"
ignore_roles = [
    "attr",
    "class",
    "doc",
    "eq",
    "exc",
    "file",
    "footcite",
    "footcite:t",
    "func",
    "gh",
    "kbd",
    "meth",
    "mod",
    "newcontrib",
    "py:mod",
    "py:obj",
    "obj",
    "ref",
    "samp",
    "term",
]
ignore_directives = [
    "autoclass",
    "autofunction",
    "automodule",
    "autosummary",
    "bibliography",
    "cssclass",
    "currentmodule",
    "dropdown",
    "footbibliography",
    "glossary",
    "graphviz",
    "grid",
    "highlight",
    "minigallery",
    "tabularcolumns",
    "toctree",
    "rst-class",
    "tab-set",
    "towncrier-draft-entries",
]
ignore_messages = "^.*(Unknown target name|Undefined substitution referenced)[^`]*$"
